### ISSUE TITLE
Box Art and Nix

### ISSUE THREAD

**Issue by Tech180** [Rolv-Apneseth/rofi-games#19]
I've been following this github since it was announced on reddit a while back and was wondering if you could make it avaliable through nix either via package or flake?

Also for you additional box art you could always use the IGDB. The box art has a lot going for it, but some of them can be a little off and you can't pick which box art you want.

**Comment by Rolv-Apneseth** [comment]
> I've been following this github since it was announced on reddit a while back and was wondering if you could make it avaliable through nix either via package or flake?

Thanks for following! I don't use NixOS but I could look into it. I do plan to migrate at some stage (though I've heard people have issues with setting up a good developer environment). Do you know where I'd get started on making it available via `flake`, and would you be willing to test for me?

> Also for you additional box art you could always use the IGDB. The box art has a lot going for it, but some of them can be a little off and you can't pick which box art you want.

What do you mean by this sorry? If you mean I should use the API - I'd rather keep the scope of this simple, and avoid making network requests. All the images should be available locally. Plus, I would assume that having to fetch images would slow it down substantially.

**Comment by zDyanTB** [comment]
So, either you [compile](https://nixos.org/manual/nixpkgs/stable/#rust) or you can [request](https://github.com/NixOS/nixpkgs/issues/301374) on nixpkgs.

**Comment by Rolv-Apneseth** [comment]
Oh, cool thanks for opening that

**Comment by TomaSajt** [comment]
Opened a PR in nixpkgs, the only slight issue with packaging this was that the project has `Cargo.lock` in the `.gitignore` list, which is unfortunate, because nix likes to work off of lockfiles. Maybe consider adding it back into source control.

https://github.com/Rolv-Apneseth/rofi-games/blob/edb88fb24a4b3582bd8ed8bb98a82fb51b9fa2cb/.gitignore#L6-L8

BTW, this comment about "libraries" means rust libraries, not shared libraries, I think.

**Comment by Rolv-Apneseth** [comment]
Nice, thanks. Yeah I'll remove the `Cargo.lock` from the `.gitignore` tomorrow when I get a minute

**Comment by Rolv-Apneseth** [comment]
That's removed from `.gitignore` now

**Comment by TomaSajt** [comment]
Great, thanks :)

**Comment by TomaSajt** [comment]
Okay, so I tried out the new version, but it looks like you bumped the version of the package without updating the lockfile / running the program, so the lockfile still says it's the older version. Could you possibly commit the updated lockfile?

**Comment by Rolv-Apneseth** [comment]
I'm not familiar `nixpkgs`, but will you include the theme files somehow? I see only these lines:

```bash
mkdir $out/lib/rofi
mv $out/lib/librofi_games.so $out/lib/rofi/games.so
```

**Comment by TomaSajt** [comment]
> I'm not familiar `nixpkgs`, but will you include the theme files somehow? I see only these lines:
> 
> ```shell
> mkdir $out/lib/rofi
> mv $out/lib/librofi_games.so $out/lib/rofi/games.so
> ```

I'll see what I can do about it.

**Comment by TomaSajt** [comment]
By the way, the lockfile is still not perfect. When I try to run the project, it still wants to regenerate it. Here's the diff:
```diff
diff --git a/Cargo.lock b/Cargo.lock
index 16c2518..5df7fb3 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -293,9 +293,9 @@ dependencies = [

 [[package]]
 name = "itertools"
-version = "0.12.1"
+version = "0.11.0"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "ba291022dbbd398a455acf126c1e341954079855bc60dfdda641363bd6922569"
+checksum = "b1c173a5686ce8bfa551b3563d0c2170bf24ca44da99c7ca4bfdab5418c3fe57"
 dependencies = [
  "either",
 ]
@@ -309,6 +309,8 @@ checksum = "e2abad23fbc42b3700f2f279844dc832adb2b2eb069b2df918f455c4e18cc646"
 [[package]]
 name = "lib_game_detector"
 version = "0.0.3"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "4d266721980ea6f6d859bd8002bef65e20c49ce734c4b5fe8ea8d24a126a0c02"
 dependencies = [
  "anyhow",
  "cfg-if",
```

I wonder how this could have happened. Have you added you local version of `lib_game_detector` to be resolvable locally?
Looks like `itertools` is only `1.12` on the `main` branch of `lib_game_detector`

**Comment by Tech180** [comment]
> > I've been following this github since it was announced on reddit a while back and was wondering if you could make it avaliable through nix either via package or flake?
> 
> Thanks for following! I don't use NixOS but I could look into it. I do plan to migrate at some stage (though I've heard people have issues with setting up a good developer environment). Do you know where I'd get started on making it available via `flake`, and would you be willing to test for me?
> 
> > Also for you additional box art you could always use the IGDB. The box art has a lot going for it, but some of them can be a little off and you can't pick which box art you want.
> 
> What do you mean by this sorry? If you mean I should use the API - I'd rather keep the scope of this simple, and avoid making network requests. All the images should be available locally. Plus, I would assume that having to fetch images would slow it down substantially.

sorry i took so long, but yes i would be more than willing to test

**Comment by Rolv-Apneseth** [comment]
Hadn't actually noticed this previously, but make sure you add a reaction to [this PR](https://github.com/NixOS/nixpkgs/pull/301397) if you're following here waiting for this package to get added to nix. I assume they evaluate what's worth reviewing based on that

**Comment by Rolv-Apneseth** [comment]
Nice, thanks again
