### ISSUE TITLE
No matching entry found

### ISSUE THREAD

**Issue by Megane0103** [Rolv-Apneseth/rofi-games#28]
Getting these errors when launching rofi-games with this command: `rofi -modi games -show games -theme games-default`.

```
ERROR rofi_games::config: 67: No matching entry found for the title 'Devil May Cry 5'. All fields for the custom entry must be provided.
ERROR rofi_games::config: 67: No matching entry found for the title 'Elden Ring'. All fields for the custom entry must be provided.
ERROR rofi_games::config: 67: No matching entry found for the title 'Final Fantasy VII Remake Intergrade'. All fields for the custom entry must be provided.
ERROR rofi_games::config: 67: No matching entry found for the title 'Ghost of Tsushima'. All fields for the custom entry must be provided.
```

This is my `config.toml`

```
box_art_dir = "/home/megane/.config/rofi-games/box-art"

[[entries]]
title = "Devil May Cry 5"
launch_command = "lutris lutris:rungame/devil-may-cry-5"
path_box_art = "devil_may_cry_5.png"

[[entries]]
title = "Elden Ring"
launch_command = "lutris lutris:rungame/elden-ring"
path_box_art = "elden_ring.png"

[[entries]]
title = "Final Fantasy VII Remake Intergrade"
launch_command = "lutris lutris:rungame/final-fantasy-iiv"
path_box_art = "final_fantasy_vii_remake_intergrade.png"

[[entries]]
title = "Ghost of Tsushima"
launch_command = "lutris lutris:rungame/ghost-of-tsushima"
path_box_art = "ghost_of_tsushima.png"
```

**Comment by Rolv-Apneseth** [comment]
Yeah they're missing the `path_game_dir`. This is what a fully custom entry is supposed to look like:

```toml
# Define a new custom entry
[[entries]]
title = "GDLauncher"
launch_command = "gdlauncher"
path_box_art = "gdlauncher.png"
path_game_dir = "/opt/GDLauncher"
```

Might makes sense to make the path optional, what do you think?

Also - if these are just Lutris games, have you tried removing the `launch_command`? The tool should parse your Lutris games and as long as the title matches, it should replace the box art image with your custom ones.

**Comment by Megane0103** [comment]
It works after adding `path_game_dir`. I just thought it wasn't necessary since Lutris doesn't need it.

**Comment by Rolv-Apneseth** [comment]
Technically none of them do - it's the directory that get's opened when pressing `Shift+Enter`. I can make it optional.

Again though, `rofi-games` should be parsing your Lutris games by default, and if you're only trying to override the box art, all you need is a `title` to match against and the `path_box_art` so try only including those 2 fields and see if it works
