### ISSUE TITLE
Feature Request: Add Gamepad Support for Selecting and Launching Games

### ISSUE THREAD

**Issue by Megane0103** [Rolv-Apneseth/rofi-games#29]
I think it would be a cool feature.

**Comment by Rolv-Apneseth** [comment]
This is only a `rofi` plugin, so if it's not possible with `rofi` it won't be possible with this. I can't find anything about gamepad support in `rofi` issues but if you figure it out let me know (maybe something with the [custom keybinds](https://github.com/davatorium/rofi/blob/next/doc/rofi-keys.5.markdown), idk).

**Comment by HelmicNewciv** [comment]
If you're using Steam, adding your gamepad to Steam Input will give it a desktop configuration.  From there, you can set the gemapd's left joystick to act as arrow keys, set the right stick to act as a mouse, set a button like X to open Steam's virtual keyboard to type in a game name to filter it, and then A as Enter and B as Escape.  Very useful to have in general when using a desktop computer with a gamepad.
