### ISSUE TITLE
installation not working on openSUSE

### ISSUE THREAD

**Issue by jpringle1** [Rolv-Apneseth/rofi-games#30]
Not sure if i've missed something dumb, but i've tried installing using both the just and manual methods, and though both methods seem to finish installing without issue, i find that i can't run `rofi-games` at all.

I suspect that i might be trying to use this wrong... in my rofi config, i have this line: `modi: "drun,games:rofi-games"`
then i try to run `rofi -modi games -show games -theme games-default` i get the rofi error saying that mode isn't available.

Have i misunderstood how to use this, or is there something that's gone wrong with the installation?

**Comment by Rolv-Apneseth** [comment]
No yeah that should work. Must not be installing correctly. Are you running Wayland? Also can you give me the output of `rofi -v`

**Comment by jpringle1** [comment]
yeh i'm on wayland, specifically running swaywm.

I'm on rofi version 1.7.5

**Comment by Rolv-Apneseth** [comment]
Is that the exact version output? Asking because `rofi -v` is how the program decides whether to compile for the current `rofi` version or the next one, since the `rofi` fork for Wayland uses the latest changes from `rofi` and so is actually further along than `1.7.5`

**Comment by jpringle1** [comment]
yep, that's the exact output of that command

**Comment by jpringle1** [comment]
Actually... i don't think i'm running the wayland for. I installed rofi on x11, then moved over to wayland. It works fine other than this, so i had no reason to think i'd need to look for another version. Might that be causing a problem?

**Comment by Rolv-Apneseth** [comment]
Might be, but it definitely didn't used to before.

If you're using the regular `rofi` and the version output is `Version: 1.7.5` then it should correctly assume you're on the current version and compile accordingly. Must be something going wrong there.

Just to be sure can you paste the _exact_ output of the command so I can verify?

**Comment by jpringle1** [comment]
Just uninstalled the x11 version and installed the wayland fork. I'm now getting this output
`Version: 1.7.5+wayland3-dev`

**Comment by Rolv-Apneseth** [comment]
You would need to reinstall `rofi-games` and make sure it rebuilds when switching to that fork. You can stay on the main `rofi` if you want though as that fork might also break other plugins you're running such as `rofi-emoji`, `rofi-calc` etc.

**Comment by jpringle1** [comment]
Just reinstalled, nothings changed. I'm gonna stay on the wayland version for now.

**Comment by Rolv-Apneseth** [comment]
Maybe the plugins dir is different on openSUSE, what's the output of `pkg-config --variable pluginsdir rofi`.

Otherwise, could you test manually installing it for me if you have the repo available locally?

First way, this one installs for 1.7.5:

```bash
cargo build --release --lib
sudo cp target/release/librofi_games.so /usr/lib/rofi/games.so
```

Check if that one works, otherwise do the same but with the flag so it know to build for a newer `rofi` version:

```bash
RUSTFLAGS="--cfg rofi_next" cargo build --release --lib
sudo cp target/release/librofi_games.so /usr/lib/rofi/games.so
```

**Comment by jpringle1** [comment]
That first command doesn't output anything at all.

i attempted both manual installation methods, but nothing changed

**Comment by Rolv-Apneseth** [comment]
How about `ls /lib/rofi`?

**Comment by Rolv-Apneseth** [comment]
Just trying to figure out where your plugins are supposed to go. Are there other plugins in `/usr/lib/rofi/`?

**Comment by jpringle1** [comment]
that directory contains only `games.so`, which just contains a bunch of indecipherable glyphs

**Comment by jpringle1** [comment]
wait that's given me an idea, i'll try something

**Comment by Rolv-Apneseth** [comment]
Yeah that's compiled, you wouldn't be able to read that.

> that directory

Which one? Might also be `/lib/rofi`.

**Comment by jpringle1** [comment]
both `/usr/lib/rofi/` and `/lib/rofi` contains only contain `games.so`

**Comment by Rolv-Apneseth** [comment]
Uh oh, gotta find where `rofi` is expecting the plugin libraries on openSUSE. Let me look up some commands

**Comment by Rolv-Apneseth** [comment]
I think it's `rpm -ql rofi` (or whatever the name for the wayland fork is) to list what files that package provides, could you try that?

**Comment by jpringle1** [comment]
Output of `rpm -ql rofi`:

```
/usr/bin/rofi
/usr/bin/rofi-sensible-terminal
/usr/bin/rofi-theme-selector
/usr/share/applications/rofi-theme-selector.desktop
/usr/share/applications/rofi.desktop
/usr/share/doc/packages/rofi-wayland
/usr/share/doc/packages/rofi-wayland/Changelog
/usr/share/doc/packages/rofi-wayland/README.md
/usr/share/icons/hicolor/scalable/apps/rofi.svg
/usr/share/licenses/rofi-wayland
/usr/share/licenses/rofi-wayland/COPYING
/usr/share/man/man1/rofi-sensible-terminal.1.gz
/usr/share/man/man1/rofi-theme-selector.1.gz
/usr/share/man/man1/rofi.1.gz
/usr/share/man/man5/rofi-debugging.5.gz
/usr/share/man/man5/rofi-dmenu.5.gz
/usr/share/man/man5/rofi-keys.5.gz
/usr/share/man/man5/rofi-script.5.gz
/usr/share/man/man5/rofi-theme.5.gz
/usr/share/rofi
/usr/share/rofi/themes
/usr/share/rofi/themes/Adapta-Nokto.rasi
/usr/share/rofi/themes/Arc-Dark.rasi
/usr/share/rofi/themes/Arc.rasi
/usr/share/rofi/themes/DarkBlue.rasi
/usr/share/rofi/themes/Indego.rasi
/usr/share/rofi/themes/Monokai.rasi
/usr/share/rofi/themes/Paper.rasi
/usr/share/rofi/themes/android_notification.rasi
/usr/share/rofi/themes/arthur.rasi
/usr/share/rofi/themes/blue.rasi
/usr/share/rofi/themes/c64.rasi
/usr/share/rofi/themes/dmenu.rasi
/usr/share/rofi/themes/docu.rasi
/usr/share/rofi/themes/fancy.rasi
/usr/share/rofi/themes/fancy2.rasi
/usr/share/rofi/themes/fullscreen-preview.rasi
/usr/share/rofi/themes/glue_pro_blue.rasi
/usr/share/rofi/themes/gruvbox-common.rasinc
/usr/share/rofi/themes/gruvbox-dark-hard.rasi
/usr/share/rofi/themes/gruvbox-dark-soft.rasi
/usr/share/rofi/themes/gruvbox-dark.rasi
/usr/share/rofi/themes/gruvbox-light-hard.rasi
/usr/share/rofi/themes/gruvbox-light-soft.rasi
/usr/share/rofi/themes/gruvbox-light.rasi
/usr/share/rofi/themes/iggy.jpg
/usr/share/rofi/themes/iggy.rasi
/usr/share/rofi/themes/lb.rasi
/usr/share/rofi/themes/material.rasi
/usr/share/rofi/themes/paper-float.rasi
/usr/share/rofi/themes/purple.rasi
/usr/share/rofi/themes/sidebar-v2.rasi
/usr/share/rofi/themes/sidebar.rasi
/usr/share/rofi/themes/solarized.rasi
/usr/share/rofi/themes/solarized_alternate.rasi
```

**Comment by Rolv-Apneseth** [comment]
Hmm not helpful, guess we would need to run it on a plugin not `rofi` itself.

Just thought of something else, what about `ls /usr/lib64/rofi`? Or some other `lib` folder in `/usr`?

**Comment by jpringle1** [comment]
`ls /usr/lib64/rofi` - no such file or directory

i searched every folder in `/usr/`, but none of them contain anything called rofi

**Comment by Rolv-Apneseth** [comment]
Damn. Is there a directory or symlink at `/lib` or `/lib64`?

**Comment by jpringle1** [comment]
no :/

**Comment by Rolv-Apneseth** [comment]
Would you mind installing a different plugin, like `rofi-emoji`, and running `rpm -ql` for it to see where they put it? I'll go have a look at some other plugins' code as well and report back if I find anything

**Comment by jpringle1** [comment]
There, we go, that helped me figure it out!

So your hunch was right earlier on, the correct directory for the games.so file is `/usr/lib64/rofi`. But that directory didn't exist for me because i didn't have any plugins installed (at least using the traditional method). It works now. 

However one thing to note: i needed the change the rofi config file to be just `modi: "games"` instead of `modi: "games:rofi-games"`.

Thanks for all your help, i appreciate it!

**Comment by Rolv-Apneseth** [comment]
> It works now

Glad to hear it. I'll have to look into how to set the correct library path automatically.

> However one thing to note: i needed the change the rofi config file to be just `modi: "games"` instead of `modi: "games:rofi-games"`.

Ah yeah I changed it but didn't update the readme I think thanks for pointing it out.

**Comment by Rolv-Apneseth** [comment]
I created [a branch](https://github.com/Rolv-Apneseth/rofi-games/tree/change-fallback-plugins-dir) with a change to the install script, would you mind testing it out for me if you have some time? Just simply checking if `/usr/lib64` exists and using that if it does, so it should be fine.

You can clone that branch using `git clone https://github.com/Rolv-Apneseth/rofi-games.git -b change-fallback-plugins-dir` and then do `sudo just install` from within that directory.

**Comment by jpringle1** [comment]
My bad, only just saw this notification. I should be able to try this in the next few days

**Comment by Rolv-Apneseth** [comment]
All good, no need to switch branches now though as it's merged (hopefully it works lol)

**Comment by jpringle1** [comment]
Just tested the new branch, seems to work fine for me :)

**Comment by Rolv-Apneseth** [comment]
Nice! Thanks for letting me know
