### ISSUE TITLE
Help with custom entries

### ISSUE THREAD

**Issue by mobedoor** [Rolv-Apneseth/rofi-games#32]
Hi. My use case is compressing games into [dwarfs](https://github.com/mhx/dwarfs) archives and using a script "launchr" to launch them.  I can't figure out how to get custom entries working
Both
```
[[entries]]
title = "TESV"
path_box_art = "/home/user/Downloads/TESV.jpg"
launch_command = "launchr TESV.dwarfs"
path_game_dir = "/data/media/games/"
```
and 
```[[entries]]
title = "TESV"
path_box_art = "/home/user/Downloads/TESV.jpg"
launch_command = "launchr /data/media/games/TESV.dwarfs"
#path_game_dir = ""
```
do not work. My script is added to path. I'd appreciate help with this.

**Comment by Rolv-Apneseth** [comment]
Can you give me the output of this:

```rofi -modi games -show games -theme games-default```

**Comment by mobedoor** [comment]
I figured it out. The issue was spaces in the filename. Enclosing game path in single quotes fixed the issue. 
Obviously you couldn't spot that since the example I posted doesn't have those issues😅 .
> Pretty cool btw - you do this to save disk space I assume? 
That and one big file is easier to backup. 
> Did you really manage to get the full Skyrim compressed and still playable?
Yeah. With SSD's, the game runs pretty fast. There are stutters in HDD's though.

**Comment by Rolv-Apneseth** [comment]
Nice, glad you got it sorted

> That and one big file is easier to backup. Using an overlay with it, means you can mess around in the game folder with mods and the like without worrying about messing stuff up.

Makes sense yeah, that's awesome
